export const ALL_COUNTRIES: { name: string; abbr: string; continent: string }[] = [
    // Африка
    { name: "Ангола", abbr: "ao", continent: "Африка" }, { name: "Буркина Фасо", abbr: "bf", continent: "Африка" },
    { name: "Бурунди", abbr: "bi", continent: "Африка" }, { name: "Бенин", abbr: "bj", continent: "Африка" },
    { name: "Ботсвана", abbr: "bw", continent: "Африка" }, { name: "ДР Конго", abbr: "cd", continent: "Африка" },
    { name: "Централноафриканска република", abbr: "cf", continent: "Африка" }, { name: "Република Конго", abbr: "cg", continent: "Африка" },
    { name: "Кот д'Ивоар", abbr: "ci", continent: "Африка" }, { name: "Камерун", abbr: "cm", continent: "Африка" },
    { name: "Кабо Верде", abbr: "cv", continent: "Африка" }, { name: "Джибути", abbr: "dj", continent: "Африка" },
    { name: "Алжир", abbr: "dz", continent: "Африка" }, { name: "Египет", abbr: "eg", continent: "Африка" },
    { name: "Западна Сахара", abbr: "eh", continent: "Африка" }, { name: "Еритрея", abbr: "er", continent: "Африка" },
    { name: "Етиопия", abbr: "et", continent: "Африка" }, { name: "Габон", abbr: "ga", continent: "Африка" },
    { name: "Гана", abbr: "gh", continent: "Африка" }, { name: "Гамбия", abbr: "gm", continent: "Африка" },
    { name: "Гвинея", abbr: "gn", continent: "Африка" }, { name: "Екваториална Гвинея", abbr: "gq", continent: "Африка" },
    { name: "Гвинея-Бисау", abbr: "gw", continent: "Африка" }, { name: "Кения", abbr: "ke", continent: "Африка" },
    { name: "Коморски острови", abbr: "km", continent: "Африка" }, { name: "Либерия", abbr: "lr", continent: "Африка" },
    { name: "Лесото", abbr: "ls", continent: "Африка" }, { name: "Либия", abbr: "ly", continent: "Африка" },
    { name: "Мароко", abbr: "ma", continent: "Африка" }, { name: "Мадагаскар", abbr: "mg", continent: "Африка" },
    { name: "Мали", abbr: "ml", continent: "Африка" }, { name: "Мавритания", abbr: "mr", continent: "Африка" },
    { name: "Мавриций", abbr: "mu", continent: "Африка" }, { name: "Малави", abbr: "mw", continent: "Африка" },
    { name: "Мозамбик", abbr: "mz", continent: "Африка" }, { name: "Намибия", abbr: "na", continent: "Африка" },
    { name: "Нигер", abbr: "ne", continent: "Африка" }, { name: "Нигерия", abbr: "ng", continent: "Африка" },
    { name: "Реюнион", abbr: "re", continent: "Африка" }, { name: "Руанда", abbr: "rw", continent: "Африка" },
    { name: "Сейшели", abbr: "sc", continent: "Африка" }, { name: "Судан", abbr: "sd", continent: "Африка" },
    { name: "Света Елена, Възнесение и Тристан да Куня", abbr: "sh", continent: "Африка" }, { name: "Сиера Леоне", abbr: "sl", continent: "Африка" },
    { name: "Сенегал", abbr: "sn", continent: "Африка" }, { name: "Сомалия", abbr: "so", continent: "Африка" },
    { name: "Южен Судан", abbr: "ss", continent: "Африка" }, { name: "Сао Томе и Принсипи", abbr: "st", continent: "Африка" },
    { name: "Есватини (Свазиленд)", abbr: "sz", continent: "Африка" }, { name: "Чад", abbr: "td", continent: "Африка" },
    { name: "Того", abbr: "tg", continent: "Африка" }, { name: "Тунис", abbr: "tn", continent: "Африка" },
    { name: "Танзания", abbr: "tz", continent: "Африка" }, { name: "Уганда", abbr: "ug", continent: "Африка" },
    { name: "Майот", abbr: "yt", continent: "Африка" }, { name: "Южна Африка", abbr: "za", continent: "Африка" },
    { name: "Замбия", abbr: "zm", continent: "Африка" }, { name: "Зимбабве", abbr: "zw", continent: "Африка" },
    // Азия
    { name: "Обединени арабски емирства", abbr: "ae", continent: "Азия" }, { name: "Афганистан", abbr: "af", continent: "Азия" },
    { name: "Армения", abbr: "am", continent: "Азия" }, { name: "Азербайджан", abbr: "az", continent: "Азия" },
    { name: "Бангладеш", abbr: "bd", continent: "Азия" }, { name: "Бахрейн", abbr: "bh", continent: "Азия" },
    { name: "Бруней", abbr: "bn", continent: "Азия" }, { name: "Бутан", abbr: "bt", continent: "Азия" },
    { name: "Кокосови (Кийлинг) острови", abbr: "cc", continent: "Азия" }, { name: "Китай", abbr: "cn", continent: "Азия" },
    { name: "Кипър", abbr: "cy", continent: "Азия" }, { name: "Грузия", abbr: "ge", continent: "Азия" },
    { name: "Хонконг", abbr: "hk", continent: "Азия" }, { name: "Индонезия", abbr: "id", continent: "Азия" },
    { name: "Израел", abbr: "il", continent: "Азия" }, { name: "Индия", abbr: "in", continent: "Азия" },
    { name: "Британска индоокеанска територия", abbr: "io", continent: "Азия" }, { name: "Ирак", abbr: "iq", continent: "Азия" },
    { name: "Иран", abbr: "ir", continent: "Азия" }, { name: "Йордания", abbr: "jo", continent: "Азия" },
    { name: "Япония", abbr: "jp", continent: "Азия" }, { name: "Киргизстан", abbr: "kg", continent: "Азия" },
    { name: "Камбоджа", abbr: "kh", continent: "Азия" }, { name: "Северна Корея", abbr: "kp", continent: "Азия" },
    { name: "Южна Корея", abbr: "kr", continent: "Азия" }, { name: "Кувейт", abbr: "kw", continent: "Азия" },
    { name: "Казахстан", abbr: "kz", continent: "Азия" }, { name: "Лаос", abbr: "la", continent: "Азия" },
    { name: "Ливан", abbr: "lb", continent: "Азия" }, { name: "Шри Ланка", abbr: "lk", continent: "Азия" },
    { name: "Мианмар", abbr: "mm", continent: "Азия" }, { name: "Монголия", abbr: "mn", continent: "Азия" },
    { name: "Макао", abbr: "mo", continent: "Азия" }, { name: "Малдиви", abbr: "mv", continent: "Азия" },
    { name: "Малайзия", abbr: "my", continent: "Азия" }, { name: "Непал", abbr: "np", continent: "Азия" },
    { name: "Оман", abbr: "om", continent: "Азия" }, { name: "Филипини", abbr: "ph", continent: "Азия" },
    { name: "Пакистан", abbr: "pk", continent: "Азия" }, { name: "Палестина", abbr: "ps", continent: "Азия" },
    { name: "Катар", abbr: "qa", continent: "Азия" }, { name: "Русия", abbr: "ru", continent: "Азия" },
    { name: "Саудитска Арабия", abbr: "sa", continent: "Азия" }, { name: "Сингапур", abbr: "sg", continent: "Азия" },
    { name: "Сирия", abbr: "sy", continent: "Азия" }, { name: "Тайланд", abbr: "th", continent: "Азия" },
    { name: "Таджикистан", abbr: "tj", continent: "Азия" }, { name: "Източен Тимор", abbr: "tl", continent: "Азия" },
    { name: "Туркменистан", abbr: "tm", continent: "Азия" }, { name: "Турция", abbr: "tr", continent: "Азия" },
    { name: "Тайван", abbr: "tw", continent: "Азия" }, { name: "Узбекистан", abbr: "uz", continent: "Азия" },
    { name: "Виетнам", abbr: "vn", continent: "Азия" }, { name: "Йемен", abbr: "ye", continent: "Азия" },
    // Европа
    { name: "Андора", abbr: "ad", continent: "Европа" }, { name: "Албания", abbr: "al", continent: "Европа" },
    { name: "Австрия", abbr: "at", continent: "Европа" }, { name: "Оландски острови", abbr: "ax", continent: "Европа" },
    { name: "Босна и Херцеговина", abbr: "ba", continent: "Европа" }, { name: "Белгия", abbr: "be", continent: "Европа" },
    { name: "България", abbr: "bg", continent: "Европа" }, { name: "Беларус", abbr: "by", continent: "Европа" },
    { name: "Швейцария", abbr: "ch", continent: "Европа" }, { name: "Чехия", abbr: "cz", continent: "Европа" },
    { name: "Германия", abbr: "de", continent: "Европа" }, { name: "Дания", abbr: "dk", continent: "Европа" },
    { name: "Естония", abbr: "ee", continent: "Европа" }, { name: "Испания", abbr: "es", continent: "Европа" },
    { name: "Финландия", abbr: "fi", continent: "Европа" }, { name: "Фарьорски острови", abbr: "fo", continent: "Европа" },
    { name: "Франция", abbr: "fr", continent: "Европа" }, { name: "Обединено кралство", abbr: "gb", continent: "Европа" },
    { name: "Гърнси", abbr: "gg", continent: "Европа" }, { name: "Гибралтар", abbr: "gi", continent: "Европа" },
    { name: "Гърция", abbr: "gr", continent: "Европа" }, { name: "Хърватия", abbr: "hr", continent: "Европа" },
    { name: "Унгария", abbr: "hu", continent: "Европа" }, { name: "Ирландия", abbr: "ie", continent: "Европа" },
    { name: "Остров Ман", abbr: "im", continent: "Европа" }, { name: "Исландия", abbr: "is", continent: "Европа" },
    { name: "Италия", abbr: "it", continent: "Европа" }, { name: "Джърси", abbr: "je", continent: "Европа" },
    { name: "Лихтенщайн", abbr: "li", continent: "Европа" }, { name: "Литва", abbr: "lt", continent: "Европа" },
    { name: "Люксембург", abbr: "lu", continent: "Европа" }, { name: "Латвия", abbr: "lv", continent: "Европа" },
    { name: "Монако", abbr: "mc", continent: "Европа" }, { name: "Молдова", abbr: "md", continent: "Европа" },
    { name: "Черна гора", abbr: "me", continent: "Европа" }, { name: "Северна Македония", abbr: "mk", continent: "Европа" },
    { name: "Малта", abbr: "mt", continent: "Европа" }, { name: "Нидерландия", abbr: "nl", continent: "Европа" },
    { name: "Норвегия", abbr: "no", continent: "Европа" }, { name: "Полша", abbr: "pl", continent: "Европа" },
    { name: "Португалия", abbr: "pt", continent: "Европа" }, { name: "Румъния", abbr: "ro", continent: "Европа" },
    { name: "Сърбия", abbr: "rs", continent: "Европа" }, { name: "Швеция", abbr: "se", continent: "Европа" },
    { name: "Словения", abbr: "si", continent: "Европа" }, { name: "Свалбард и Ян Майен", abbr: "sj", continent: "Европа" },
    { name: "Словакия", abbr: "sk", continent: "Европа" }, { name: "Сан Марино", abbr: "sm", continent: "Европа" },
    { name: "Украйна", abbr: "ua", continent: "Европа" }, { name: "Ватикан (Свети престол)", abbr: "va", continent: "Европа" },
    { name: "Косово", abbr: "xk", continent: "Европа" },
    // Северна Америка
    { name: "Антигуа и Барбуда", abbr: "ag", continent: "Северна Америка" }, { name: "Ангуила", abbr: "ai", continent: "Северна Америка" },
    { name: "Аруба", abbr: "aw", continent: "Северна Америка" }, { name: "Барбадос", abbr: "bb", continent: "Северна Америка" },
    { name: "Сен Бартелеми", abbr: "bl", continent: "Северна Америка" }, { name: "Бермуди", abbr: "bm", continent: "Северна Америка" },
    { name: "Карибска Нидерландия", abbr: "bq", continent: "Северна Америка" }, { name: "Бахамски острови", abbr: "bs", continent: "Северна Америка" },
    { name: "Белиз", abbr: "bz", continent: "Северна Америка" }, { name: "Канада", abbr: "ca", continent: "Северна Америка" },
    { name: "Коста Рика", abbr: "cr", continent: "Северна Америка" }, { name: "Куба", abbr: "cu", continent: "Северна Америка" },
    { name: "Кюрасао", abbr: "cw", continent: "Северна Америка" }, { name: "Доминика", abbr: "dm", continent: "Северна Америка" },
    { name: "Доминиканска република", abbr: "do", continent: "Северна Америка" }, { name: "Гренада", abbr: "gd", continent: "Северна Америка" },
    { name: "Гренландия", abbr: "gl", continent: "Северна Америка" }, { name: "Гваделупа", abbr: "gp", continent: "Северна Америка" },
    { name: "Гватемала", abbr: "gt", continent: "Северна Америка" }, { name: "Хондурас", abbr: "hn", continent: "Северна Америка" },
    { name: "Хаити", abbr: "ht", continent: "Северна Америка" }, { name: "Ямайка", abbr: "jm", continent: "Северна Америка" },
    { name: "Сейнт Китс и Невис", abbr: "kn", continent: "Северна Америка" }, { name: "Кайманови острови", abbr: "ky", continent: "Северна Америка" },
    { name:"Сейнт Лусия", abbr: "lc", continent: "Северна Америка" }, { name: "Сен Мартен", abbr: "mf", continent: "Северна Америка" },
    { name: "Мартиника", abbr: "mq", continent: "Северна Америка" }, { name: "Монсерат", abbr: "ms", continent: "Северна Америка" },
    { name: "Мексико", abbr: "mx", continent: "Северна Америка" }, { name: "Никарагуа", abbr: "ni", continent: "Северна Америка" },
    { name: "Панама", abbr: "pa", continent: "Северна Америка" }, { name: "Сен Пиер и Микелон", abbr: "pm", continent: "Северна Америка" },
    { name: "Пуерто Рико", abbr: "pr", continent: "Северна Америка" }, { name: "Ел Салвадор", abbr: "sv", continent: "Северна Америка" },
    { name: "Синт Мартен", abbr: "sx", continent: "Северна Америка" }, { name: "Търкс и Кайкос", abbr: "tc", continent: "Северна Америка" },
    { name: "Тринидад и Тобаго", abbr: "tt", continent: "Северна Америка" }, { name: "Съединени щати", abbr: "us", continent: "Северна Америка" },
    { name: "Сейнт Винсент и Гренадини", abbr: "vc", continent: "Северна Америка" }, { name: "Британски Вирджински острови", abbr: "vg", continent: "Северна Америка" },
    { name: "Американски Вирджински острови", abbr: "vi", continent: "Северна Америка" },
    // Океания
    { name: "Американска Самоа", abbr: "as", continent: "Океания" }, { name: "Австралия", abbr: "au", continent: "Океания" },
    { name: "Острови Кук", abbr: "ck", continent: "Океания" }, { name: "Фиджи", abbr: "fj", continent: "Океания" },
    { name: "Микронезия", abbr: "fm", continent: "Океания" }, { name: "Гуам", abbr: "gu", continent: "Океания" },
    { name: "Остров Хърд и острови Макдоналд", abbr: "hm", continent: "Океания" }, { name: "Кирибати", abbr: "ki", continent: "Океания" },
    { name: "Маршалови острови", abbr: "mh", continent: "Океания" }, { name: "Северни Мариански острови", abbr: "mp", continent: "Океания" },
    { name: "Нова Каледония", abbr: "nc", continent: "Океания" }, { name: "Остров Норфолк", abbr: "nf", continent: "Океания" },
    { name: "Науру", abbr: "nr", continent: "Океания" }, { name: "Ниуе", abbr: "nu", continent: "Океания" },
    { name: "Нова Зеландия", abbr: "nz", continent: "Океания" }, { name: "Френска Полинезия", abbr: "pf", continent: "Океания" },
    { name: "Папуа Нова Гвинея", abbr: "pg", continent: "Океания" }, { name: "Питкерн", abbr: "pn", continent: "Океания" },
    { name: "Палау", abbr: "pw", continent: "Океания" }, { name: "Соломонови острови", abbr: "sb", continent: "Океания" },
    { name: "Токелау", abbr: "tk", continent: "Океания" }, { name: "Тонга", abbr: "to", continent: "Океания" },
    { name: "Тувалу", abbr: "tv", continent: "Океания" }, { name: "Малки далечни острови на САЩ", abbr: "um", continent: "Океания" },
    { name: "Вануату", abbr: "vu", continent: "Океания" }, { name: "Уолис и Футуна", abbr: "wf", continent: "Океания" },
    { name: "Самоа", abbr: "ws", continent: "Океания" },
    // Южна Америка
    { name: "Аржентина", abbr: "ar", continent: "Южна Америка" }, { name: "Боливия", abbr: "bo", continent: "Южна Америка" },
    { name: "Бразилия", abbr: "br", continent: "Южна Америка" }, { name: "Чили", abbr: "cl", continent: "Южна Америка" },
    { name: "Колумбия", abbr: "co", continent: "Южна Америка" }, { name: "Еквадор", abbr: "ec", continent: "Южна Америка" },
    { name: "Фолкландски острови", abbr: "fk", continent: "Южна Америка" }, { name: "Френска Гвиана", abbr: "gf", continent: "Южна Америка" },
    { name: "Южна Джорджия", abbr: "gs", continent: "Южна Америка" }, { name: "Гвиана", abbr: "gy", continent: "Южна Америка" },
    { name: "Перу", abbr: "pe", continent: "Южна Америка" }, { name: "Парагвай", abbr: "py", continent: "Южна Америка" },
    { name: "Суринам", abbr: "sr", continent: "Южна Америка" }, { name: "Уругвай", abbr: "uy", continent: "Южна Америка" },
    { name: "Венецуела", abbr: "ve", continent: "Южна Америка" },
    // Antarctica
    { name: "Антарктида", abbr: "aq", continent: "Antarctica" }, { name: "Остров Буве", abbr: "bv", continent: "Antarctica" },
    { name: "Френски южни и антарктически територии", abbr: "tf", continent: "Antarctica" }
];
