export const ALL_COUNTRIES: { name: string; name_en: string; abbr: string; continent: string }[] = [
    // Африка
    { name: "Ангола", name_en: "Angola", abbr: "ao", continent: "Африка" }, { name: "Буркина Фасо", name_en: "Burkina Faso", abbr: "bf", continent: "Африка" },
    { name: "Бурунди", name_en: "Burundi", abbr: "bi", continent: "Африка" }, { name: "Бенин", name_en: "Benin", abbr: "bj", continent: "Африка" },
    { name: "Ботсвана", name_en: "Botswana", abbr: "bw", continent: "Африка" }, { name: "ДР Конго", name_en: "DR Congo", abbr: "cd", continent: "Африка" },
    { name: "Централноафриканска република", name_en: "Central African Republic", abbr: "cf", continent: "Африка" }, { name: "Република Конго", name_en: "Republic of the Congo", abbr: "cg", continent: "Африка" },
    { name: "Кот д'Ивоар", name_en: "Ivory Coast", abbr: "ci", continent: "Африка" }, { name: "Камерун", name_en: "Cameroon", abbr: "cm", continent: "Африка" },
    { name: "Кабо Верде", name_en: "Cape Verde", abbr: "cv", continent: "Африка" }, { name: "Джибути", name_en: "Djibouti", abbr: "dj", continent: "Африка" },
    { name: "Алжир", name_en: "Algeria", abbr: "dz", continent: "Африка" }, { name: "Египет", name_en: "Egypt", abbr: "eg", continent: "Африка" },
    { name: "Западна Сахара", name_en: "Western Sahara", abbr: "eh", continent: "Африка" }, { name: "Еритрея", name_en: "Eritrea", abbr: "er", continent: "Африка" },
    { name: "Етиопия", name_en: "Ethiopia", abbr: "et", continent: "Африка" }, { name: "Габон", name_en: "Gabon", abbr: "ga", continent: "Африка" },
    { name: "Гана", name_en: "Ghana", abbr: "gh", continent: "Африка" }, { name: "Гамбия", name_en: "Gambia", abbr: "gm", continent: "Африка" },
    { name: "Гвинея", name_en: "Guinea", abbr: "gn", continent: "Африка" }, { name: "Екваториална Гвинея", name_en: "Equatorial Guinea", abbr: "gq", continent: "Африка" },
    { name: "Гвинея-Бисау", name_en: "Guinea-Bissau", abbr: "gw", continent: "Африка" }, { name: "Кения", name_en: "Kenya", abbr: "ke", continent: "Африка" },
    { name: "Коморски острови", name_en: "Comoros", abbr: "km", continent: "Африка" }, { name: "Либерия", name_en: "Liberia", abbr: "lr", continent: "Африка" },
    { name: "Лесото", name_en: "Lesotho", abbr: "ls", continent: "Африка" }, { name: "Либия", name_en: "Libya", abbr: "ly", continent: "Африка" },
    { name: "Мароко", name_en: "Morocco", abbr: "ma", continent: "Африка" }, { name: "Мадагаскар", name_en: "Madagascar", abbr: "mg", continent: "Африка" },
    { name: "Мали", name_en: "Mali", abbr: "ml", continent: "Африка" }, { name: "Мавритания", name_en: "Mauritania", abbr: "mr", continent: "Африка" },
    { name: "Мавриций", name_en: "Mauritius", abbr: "mu", continent: "Африка" }, { name: "Малави", name_en: "Malawi", abbr: "mw", continent: "Африка" },
    { name: "Мозамбик", name_en: "Mozambique", abbr: "mz", continent: "Африка" }, { name: "Намибия", name_en: "Namibia", abbr: "na", continent: "Африка" },
    { name: "Нигер", name_en: "Niger", abbr: "ne", continent: "Африка" }, { name: "Нигерия", name_en: "Nigeria", abbr: "ng", continent: "Африка" },
    { name: "Реюнион", name_en: "Reunion", abbr: "re", continent: "Африка" }, { name: "Руанда", name_en: "Rwanda", abbr: "rw", continent: "Африка" },
    { name: "Сейшели", name_en: "Seychelles", abbr: "sc", continent: "Африка" }, { name: "Судан", name_en: "Sudan", abbr: "sd", continent: "Африка" },
    { name: "Света Елена, Възнесение и Тристан да Куня", name_en: "Saint Helena", abbr: "sh", continent: "Африка" }, { name: "Сиера Леоне", name_en: "Sierra Leone", abbr: "sl", continent: "Африка" },
    { name: "Сенегал", name_en: "Senegal", abbr: "sn", continent: "Африка" }, { name: "Сомалия", name_en: "Somalia", abbr: "so", continent: "Африка" },
    { name: "Южен Судан", name_en: "South Sudan", abbr: "ss", continent: "Африка" }, { name: "Сао Томе и Принсипи", name_en: "Sao Tome and Principe", abbr: "st", continent: "Африка" },
    { name: "Есватини (Свазиленд)", name_en: "Eswatini", abbr: "sz", continent: "Африка" }, { name: "Чад", name_en: "Chad", abbr: "td", continent: "Африка" },
    { name: "Того", name_en: "Togo", abbr: "tg", continent: "Африка" }, { name: "Тунис", name_en: "Tunisia", abbr: "tn", continent: "Африка" },
    { name: "Танзания", name_en: "Tanzania", abbr: "tz", continent: "Африка" }, { name: "Уганда", name_en: "Uganda", abbr: "ug", continent: "Африка" },
    { name: "Майот", name_en: "Mayotte", abbr: "yt", continent: "Африка" }, { name: "Южна Африка", name_en: "South Africa", abbr: "za", continent: "Африка" },
    { name: "Замбия", name_en: "Zambia", abbr: "zm", continent: "Африка" }, { name: "Зимбабве", name_en: "Zimbabwe", abbr: "zw", continent: "Африка" },
    // Азия
    { name: "Обединени арабски емирства", name_en: "United Arab Emirates", abbr: "ae", continent: "Азия" }, { name: "Афганистан", name_en: "Afghanistan", abbr: "af", continent: "Азия" },
    { name: "Армения", name_en: "Armenia", abbr: "am", continent: "Азия" }, { name: "Азербайджан", name_en: "Azerbaijan", abbr: "az", continent: "Азия" },
    { name: "Бангладеш", name_en: "Bangladesh", abbr: "bd", continent: "Азия" }, { name: "Бахрейн", name_en: "Bahrain", abbr: "bh", continent: "Азия" },
    { name: "Бруней", name_en: "Brunei", abbr: "bn", continent: "Азия" }, { name: "Бутан", name_en: "Bhutan", abbr: "bt", continent: "Азия" },
    { name: "Кокосови (Кийлинг) острови", name_en: "Cocos (Keeling) Islands", abbr: "cc", continent: "Азия" }, { name: "Китай", name_en: "China", abbr: "cn", continent: "Азия" },
    { name: "Кипър", name_en: "Cyprus", abbr: "cy", continent: "Азия" }, { name: "Грузия", name_en: "Georgia", abbr: "ge", continent: "Азия" },
    { name: "Хонконг", name_en: "Hong Kong", abbr: "hk", continent: "Азия" }, { name: "Индонезия", name_en: "Indonesia", abbr: "id", continent: "Азия" },
    { name: "Израел", name_en: "Israel", abbr: "il", continent: "Азия" }, { name: "Индия", name_en: "India", abbr: "in", continent: "Азия" },
    { name: "Британска индоокеанска територия", name_en: "British Indian Ocean Territory", abbr: "io", continent: "Азия" }, { name: "Ирак", name_en: "Iraq", abbr: "iq", continent: "Азия" },
    { name: "Иран", name_en: "Iran", abbr: "ir", continent: "Азия" }, { name: "Йордания", name_en: "Jordan", abbr: "jo", continent: "Азия" },
    { name: "Япония", name_en: "Japan", abbr: "jp", continent: "Азия" }, { name: "Киргизстан", name_en: "Kyrgyzstan", abbr: "kg", continent: "Азия" },
    { name: "Камбоджа", name_en: "Cambodia", abbr: "kh", continent: "Азия" }, { name: "Северна Корея", name_en: "North Korea", abbr: "kp", continent: "Азия" },
    { name: "Южна Корея", name_en: "South Korea", abbr: "kr", continent: "Азия" }, { name: "Кувейт", name_en: "Kuwait", abbr: "kw", continent: "Азия" },
    { name: "Казахстан", name_en: "Kazakhstan", abbr: "kz", continent: "Азия" }, { name: "Лаос", name_en: "Laos", abbr: "la", continent: "Азия" },
    { name: "Ливан", name_en: "Lebanon", abbr: "lb", continent: "Азия" }, { name: "Шри Ланка", name_en: "Sri Lanka", abbr: "lk", continent: "Азия" },
    { name: "Мианмар", name_en: "Myanmar", abbr: "mm", continent: "Азия" }, { name: "Монголия", name_en: "Mongolia", abbr: "mn", continent: "Азия" },
    { name: "Макао", name_en: "Macau", abbr: "mo", continent: "Азия" }, { name: "Малдиви", name_en: "Maldives", abbr: "mv", continent: "Азия" },
    { name: "Малайзия", name_en: "Malaysia", abbr: "my", continent: "Азия" }, { name: "Непал", name_en: "Nepal", abbr: "np", continent: "Азия" },
    { name: "Оман", name_en: "Oman", abbr: "om", continent: "Азия" }, { name: "Филипини", name_en: "Philippines", abbr: "ph", continent: "Азия" },
    { name: "Пакистан", name_en: "Pakistan", abbr: "pk", continent: "Азия" }, { name: "Палестина", name_en: "Palestine", abbr: "ps", continent: "Азия" },
    { name: "Катар", name_en: "Qatar", abbr: "qa", continent: "Азия" }, { name: "Русия", name_en: "Russia", abbr: "ru", continent: "Азия" },
    { name: "Саудитска Арабия", name_en: "Saudi Arabia", abbr: "sa", continent: "Азия" }, { name: "Сингапур", name_en: "Singapore", abbr: "sg", continent: "Азия" },
    { name: "Сирия", name_en: "Syria", abbr: "sy", continent: "Азия" }, { name: "Тайланд", name_en: "Thailand", abbr: "th", continent: "Азия" },
    { name: "Таджикистан", name_en: "Tajikistan", abbr: "tj", continent: "Азия" }, { name: "Източен Тимор", name_en: "Timor-Leste", abbr: "tl", continent: "Азия" },
    { name: "Туркменистан", name_en: "Turkmenistan", abbr: "tm", continent: "Азия" }, { name: "Турция", name_en: "Turkey", abbr: "tr", continent: "Азия" },
    { name: "Тайван", name_en: "Taiwan", abbr: "tw", continent: "Азия" }, { name: "Узбекистан", name_en: "Uzbekistan", abbr: "uz", continent: "Азия" },
    { name: "Виетнам", name_en: "Vietnam", abbr: "vn", continent: "Азия" }, { name: "Йемен", name_en: "Yemen", abbr: "ye", continent: "Азия" },
    // Европа
    { name: "Андора", name_en: "Andorra", abbr: "ad", continent: "Европа" }, { name: "Албания", name_en: "Albania", abbr: "al", continent: "Европа" },
    { name: "Австрия", name_en: "Austria", abbr: "at", continent: "Европа" }, { name: "Оландски острови", name_en: "Aland Islands", abbr: "ax", continent: "Европа" },
    { name: "Босна и Херцеговина", name_en: "Bosnia and Herzegovina", abbr: "ba", continent: "Европа" }, { name: "Белгия", name_en: "Belgium", abbr: "be", continent: "Европа" },
    { name: "България", name_en: "Bulgaria", abbr: "bg", continent: "Европа" }, { name: "Беларус", name_en: "Belarus", abbr: "by", continent: "Европа" },
    { name: "Швейцария", name_en: "Switzerland", abbr: "ch", continent: "Европа" }, { name: "Чехия", name_en: "Czechia", abbr: "cz", continent: "Европа" },
    { name: "Германия", name_en: "Germany", abbr: "de", continent: "Европа" }, { name: "Дания", name_en: "Denmark", abbr: "dk", continent: "Европа" },
    { name: "Естония", name_en: "Estonia", abbr: "ee", continent: "Европа" }, { name: "Испания", name_en: "Spain", abbr: "es", continent: "Европа" },
    { name: "Финландия", name_en: "Finland", abbr: "fi", continent: "Европа" }, { name: "Фарьорски острови", name_en: "Faroe Islands", abbr: "fo", continent: "Европа" },
    { name: "Франция", name_en: "France", abbr: "fr", continent: "Европа" }, { name: "Обединено кралство", name_en: "United Kingdom", abbr: "gb", continent: "Европа" },
    { name: "Гърнси", name_en: "Guernsey", abbr: "gg", continent: "Европа" }, { name: "Гибралтар", name_en: "Gibraltar", abbr: "gi", continent: "Европа" },
    { name: "Гърция", name_en: "Greece", abbr: "gr", continent: "Европа" }, { name: "Хърватия", name_en: "Croatia", abbr: "hr", continent: "Европа" },
    { name: "Унгария", name_en: "Hungary", abbr: "hu", continent: "Европа" }, { name: "Ирландия", name_en: "Ireland", abbr: "ie", continent: "Европа" },
    { name: "Остров Ман", name_en: "Isle of Man", abbr: "im", continent: "Европа" }, { name: "Исландия", name_en: "Iceland", abbr: "is", continent: "Европа" },
    { name: "Италия", name_en: "Italy", abbr: "it", continent: "Европа" }, { name: "Джърси", name_en: "Jersey", abbr: "je", continent: "Европа" },
    { name: "Лихтенщайн", name_en: "Liechtenstein", abbr: "li", continent: "Европа" }, { name: "Литва", name_en: "Lithuania", abbr: "lt", continent: "Европа" },
    { name: "Люксембург", name_en: "Luxembourg", abbr: "lu", continent: "Европа" }, { name: "Латвия", name_en: "Latvia", abbr: "lv", continent: "Европа" },
    { name: "Монако", name_en: "Monaco", abbr: "mc", continent: "Европа" }, { name: "Молдова", name_en: "Moldova", abbr: "md", continent: "Европа" },
    { name: "Черна гора", name_en: "Montenegro", abbr: "me", continent: "Европа" }, { name: "Северна Македония", name_en: "North Macedonia", abbr: "mk", continent: "Европа" },
    { name: "Малта", name_en: "Malta", abbr: "mt", continent: "Европа" }, { name: "Нидерландия", name_en: "Netherlands", abbr: "nl", continent: "Европа" },
    { name: "Норвегия", name_en: "Norway", abbr: "no", continent: "Европа" }, { name: "Полша", name_en: "Poland", abbr: "pl", continent: "Европа" },
    { name: "Португалия", name_en: "Portugal", abbr: "pt", continent: "Европа" }, { name: "Румъния", name_en: "Romania", abbr: "ro", continent: "Европа" },
    { name: "Сърбия", name_en: "Serbia", abbr: "rs", continent: "Европа" }, { name: "Швеция", name_en: "Sweden", abbr: "se", continent: "Европа" },
    { name: "Словения", name_en: "Slovenia", abbr: "si", continent: "Европа" }, { name: "Свалбард и Ян Майен", name_en: "Svalbard and Jan Mayen", abbr: "sj", continent: "Европа" },
    { name: "Словакия", name_en: "Slovakia", abbr: "sk", continent: "Европа" }, { name: "Сан Марино", name_en: "San Marino", abbr: "sm", continent: "Европа" },
    { name: "Украйна", name_en: "Ukraine", abbr: "ua", continent: "Европа" }, { name: "Ватикан (Свети престол)", name_en: "Vatican City", abbr: "va", continent: "Европа" },
    { name: "Косово", name_en: "Kosovo", abbr: "xk", continent: "Европа" },
    // Северна Америка
    { name: "Антигуа и Барбуда", name_en: "Antigua and Barbuda", abbr: "ag", continent: "Северна Америка" }, { name: "Ангуила", name_en: "Anguilla", abbr: "ai", continent: "Северна Америка" },
    { name: "Аруба", name_en: "Aruba", abbr: "aw", continent: "Северна Америка" }, { name: "Барбадос", name_en: "Barbados", abbr: "bb", continent: "Северна Америка" },
    { name: "Сен Бартелеми", name_en: "Saint Barthelemy", abbr: "bl", continent: "Северна Америка" }, { name: "Бермуди", name_en: "Bermuda", abbr: "bm", continent: "Северна Америка" },
    { name: "Карибска Нидерландия", name_en: "Bonaire, Sint Eustatius and Saba", abbr: "bq", continent: "Северна Америка" }, { name: "Бахамски острови", name_en: "Bahamas", abbr: "bs", continent: "Северна Америка" },
    { name: "Белиз", name_en: "Belize", abbr: "bz", continent: "Северна Америка" }, { name: "Канада", name_en: "Canada", abbr: "ca", continent: "Северна Америка" },
    { name: "Коста Рика", name_en: "Costa Rica", abbr: "cr", continent: "Северна Америка" }, { name: "Куба", name_en: "Cuba", abbr: "cu", continent: "Северна Америка" },
    { name: "Кюрасао", name_en: "Curacao", abbr: "cw", continent: "Северна Америка" }, { name: "Доминика", name_en: "Dominica", abbr: "dm", continent: "Северна Америка" },
    { name: "Доминиканска република", name_en: "Dominican Republic", abbr: "do", continent: "Северна Америка" }, { name: "Гренада", name_en: "Grenada", abbr: "gd", continent: "Северна Америка" },
    { name: "Гренландия", name_en: "Greenland", abbr: "gl", continent: "Северна Америка" }, { name: "Гваделупа", name_en: "Guadeloupe", abbr: "gp", continent: "Северна Америка" },
    { name: "Гватемала", name_en: "Guatemala", abbr: "gt", continent: "Северна Америка" }, { name: "Хондурас", name_en: "Honduras", abbr: "hn", continent: "Северна Америка" },
    { name: "Хаити", name_en: "Haiti", abbr: "ht", continent: "Северна Америка" }, { name: "Ямайка", name_en: "Jamaica", abbr: "jm", continent: "Северна Америка" },
    { name: "Сейнт Китс и Невис", name_en: "Saint Kitts and Nevis", abbr: "kn", continent: "Северна Америка" }, { name: "Кайманови острови", name_en: "Cayman Islands", abbr: "ky", continent: "Северна Америка" },
    { name: "Сейнт Лусия", name_en: "Saint Lucia", abbr: "lc", continent: "Северна Америка" }, { name: "Сен Мартен", name_en: "Saint Martin", abbr: "mf", continent: "Северна Америка" },
    { name: "Мартиника", name_en: "Martinique", abbr: "mq", continent: "Северна Америка" }, { name: "Монсерат", name_en: "Montserrat", abbr: "ms", continent: "Северна Америка" },
    { name: "Мексико", name_en: "Mexico", abbr: "mx", continent: "Северна Америка" }, { name: "Никарагуа", name_en: "Nicaragua", abbr: "ni", continent: "Северна Америка" },
    { name: "Панама", name_en: "Panama", abbr: "pa", continent: "Северна Америка" }, { name: "Сен Пиер и Микелон", name_en: "Saint Pierre and Miquelon", abbr: "pm", continent: "Северна Америка" },
    { name: "Пуерто Рико", name_en: "Puerto Rico", abbr: "pr", continent: "Северна Америка" }, { name: "Ел Салвадор", name_en: "El Salvador", abbr: "sv", continent: "Северна Америка" },
    { name: "Синт Мартен", name_en: "Sint Maarten", abbr: "sx", continent: "Северна Америка" }, { name: "Търкс и Кайкос", name_en: "Turks and Caicos Islands", abbr: "tc", continent: "Северна Америка" },
    { name: "Тринидад и Тобаго", name_en: "Trinidad and Tobago", abbr: "tt", continent: "Северна Америка" }, { name: "Съединени щати", name_en: "United States", abbr: "us", continent: "Северна Америка" },
    { name: "Сейнт Винсент и Гренадини", name_en: "Saint Vincent and the Grenadines", abbr: "vc", continent: "Северна Америка" }, { name: "Британски Вирджински острови", name_en: "British Virgin Islands", abbr: "vg", continent: "Северна Америка" },
    { name: "Американски Вирджински острови", name_en: "U.S. Virgin Islands", abbr: "vi", continent: "Северна Америка" },
    // Океания
    { name: "Американска Самоа", name_en: "American Samoa", abbr: "as", continent: "Океания" }, { name: "Австралия", name_en: "Australia", abbr: "au", continent: "Океания" },
    { name: "Острови Кук", name_en: "Cook Islands", abbr: "ck", continent: "Океания" }, { name: "Фиджи", name_en: "Fiji", abbr: "fj", continent: "Океания" },
    { name: "Микронезия", name_en: "Micronesia", abbr: "fm", continent: "Океания" }, { name: "Гуам", name_en: "Guam", abbr: "gu", continent: "Океания" },
    { name: "Остров Хърд и острови Макдоналд", name_en: "Heard Island and McDonald Islands", abbr: "hm", continent: "Океания" }, { name: "Кирибати", name_en: "Kiribati", abbr: "ki", continent: "Океания" },
    { name: "Маршалови острови", name_en: "Marshall Islands", abbr: "mh", continent: "Океания" }, { name: "Северни Мариански острови", name_en: "Northern Mariana Islands", abbr: "mp", continent: "Океания" },
    { name: "Нова Каледония", name_en: "New Caledonia", abbr: "nc", continent: "Океания" }, { name: "Остров Норфолк", name_en: "Norfolk Island", abbr: "nf", continent: "Океания" },
    { name: "Науру", name_en: "Nauru", abbr: "nr", continent: "Океания" }, { name: "Ниуе", name_en: "Niue", abbr: "nu", continent: "Океания" },
    { name: "Нова Зеландия", name_en: "New Zealand", abbr: "nz", continent: "Океания" }, { name: "Френска Полинезия", name_en: "French Polynesia", abbr: "pf", continent: "Океания" },
    { name: "Папуа Нова Гвинея", name_en: "Papua New Guinea", abbr: "pg", continent: "Океания" }, { name: "Питкерн", name_en: "Pitcairn", abbr: "pn", continent: "Океания" },
    { name: "Палау", name_en: "Palau", abbr: "pw", continent: "Океания" }, { name: "Соломонови острови", name_en: "Solomon Islands", abbr: "sb", continent: "Океания" },
    { name: "Токелау", name_en: "Tokelau", abbr: "tk", continent: "Океания" }, { name: "Тонга", name_en: "Tonga", abbr: "to", continent: "Океания" },
    { name: "Тувалу", name_en: "Tuvalu", abbr: "tv", continent: "Океания" }, { name: "Малки далечни острови на САЩ", name_en: "United States Minor Outlying Islands", abbr: "um", continent: "Океания" },
    { name: "Вануату", name_en: "Vanuatu", abbr: "vu", continent: "Океания" }, { name: "Уолис и Футуна", name_en: "Wallis and Futuna", abbr: "wf", continent: "Океания" },
    { name: "Самоа", name_en: "Samoa", abbr: "ws", continent: "Океания" },
    // Южна Америка
    { name: "Аржентина", name_en: "Argentina", abbr: "ar", continent: "Южна Америка" }, { name: "Боливия", name_en: "Bolivia", abbr: "bo", continent: "Южна Америка" },
    { name: "Бразилия", name_en: "Brazil", abbr: "br", continent: "Южна Америка" }, { name: "Чили", name_en: "Chile", abbr: "cl", continent: "Южна Америка" },
    { name: "Колумбия", name_en: "Colombia", abbr: "co", continent: "Южна Америка" }, { name: "Еквадор", name_en: "Ecuador", abbr: "ec", continent: "Южна Америка" },
    { name: "Фолкландски острови", name_en: "Falkland Islands", abbr: "fk", continent: "Южна Америка" }, { name: "Френска Гвиана", name_en: "French Guiana", abbr: "gf", continent: "Южна Америка" },
    { name: "Южна Джорджия", name_en: "South Georgia", abbr: "gs", continent: "Южна Америка" }, { name: "Гвиана", name_en: "Guyana", abbr: "gy", continent: "Южна Америка" },
    { name: "Перу", name_en: "Peru", abbr: "pe", continent: "Южна Америка" }, { name: "Парагвай", name_en: "Paraguay", abbr: "py", continent: "Южна Америка" },
    { name: "Суринам", name_en: "Suriname", abbr: "sr", continent: "Южна Америка" }, { name: "Уругвай", name_en: "Uruguay", abbr: "uy", continent: "Южна Америка" },
    { name: "Венецуела", name_en: "Venezuela", abbr: "ve", continent: "Южна Америка" },
    // Antarctica
    { name: "Антарктида", name_en: "Antarctica", abbr: "aq", continent: "Antarctica" }, { name: "Остров Буве", name_en: "Bouvet Island", abbr: "bv", continent: "Antarctica" },
    { name: "Френски южни и антарктически територии", name_en: "French Southern Territories", abbr: "tf", continent: "Antarctica" }
];
